project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Statistical Computing"
  author: "Susan Vanderplas"
  date: "Spring 2022"
  chapters:
    - index.qmd
    - 1-getting-started.qmd
    - 2-markdown.qmd
    - 3-finding-your-way.qmd
    - 4-data-types.qmd
    - 5-vectors.qmd
    - data-structures.qmd
    - reading-data.qmd
    - functions.qmd
    - statistics.qmd
    - ttests.qmd
    - linear-modeling.qmd
    - git-github.qmd
    - references.qmd
  site-url: https://srvanderplas.github.io/Stat151/
  repo-url: https://github.com/srvanderplas/Stat151
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  toc:
    collapse: section
bibliography: references.bib
pdf-engine: xelatex
from: markdown+emoji

format:
  html:
    css: style.css
    theme: cosmo
    code-link: true

  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png

editor: visual

