name: Render and Deploy Quarto Book
on: push

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: actions/setup-python@v2

      - name: Install Python dependencies 1
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install -y python3-virtualenv
          sudo apt install -y python3-dev
          sudo apt install -y python3-venv
        shell: /bin/bash {0}

      - name: Install R dependencies
        if: runner.os == 'Linux'
        run: |
          install.packages(c("rmarkdown", "jsonlite", "reticulate", "quarto", "pak"))
        shell: Rscript {0}

      - name: Setup python virtualenv
        run: |
          reticulate::virtualenv_create("testbook", packages = c("matplotlib", "numpy"))
          reticulate::py_install("testbook", pip = T, pip_options = c("-r requirements.txt", "--no-binary=numpy"))
          reticulate::py_install("jupyter", pip = T)
        shell: Rscript {0}

      - name: "Install curl for Bioconductor"
        run: |
          # sudo apt -y install libcurl4-openssl-dev

      - name: "Install R Packages: Cache packages"
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: "Install R Packages: Restore packages"
        shell: Rscript {0}
        run: |
          pak::pkg_install("rstudio/renv")
          pak::pkg_install("hadley/emo")
          # pak::pkg_install("tidyverse/tidyverse")
          # pak::pkg_install("tidyverse/dplyr")
          # pak::pkg_install("tidyverse/tibble")
          options(renv.download.override = utils::download.file)
          # install.packages("fontawesome")
          renv::restore()

      - name: "Install Quarto and render"
        uses: pommevilla/quarto-render@main

      - name: "Deploy to gh-pages"
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
